// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/03/2026, 17:26:23
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Lenovo/Documents/GitHub/quickstore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/plugins/**/*.{js,ts,mjs}","C:/Users/Lenovo/Documents/GitHub/quickstore/composables/**/*.{js,ts,mjs}","C:/Users/Lenovo/Documents/GitHub/quickstore/utils/**/*.{js,ts,mjs}","C:/Users/Lenovo/Documents/GitHub/quickstore/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Documents/GitHub/quickstore/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;